
# Este é um exemplo de um fluxo de trabalho que é chamdo manualmente

name: Manual workflow


#Controla quando a acao ira ser executada. O worflow roda quando manualmente é executado usando a Tela ou por uma api.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Pessoa para dizer ola'
        # Default value if no value is explicitly provided
        default: 'Fabiao'
        # Input has to be provided for the workflow to run
        required: true

      idade:
        description: 'quantos anos voce tem'
        default: '43'
        required: false



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "salveMano"
  salveMano:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
      token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    # Runs a single command using the runners shell
    - name: Da um salve vei
      run: echo "É nois Broooo ${{ github.event.inputs.name }}"

      # Runs a single command using the runners shell
    - name: Diga oi
      run: echo "Oi ${{ github.event.inputs.name }}"
